id: P000643
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5875
  title: མཆོད་རྟེན་དང་ཚ་ཚ་གདབ་པའི་ཆོ་གའི་གཞུང་གསུམ་ཕྱོགས་གཏུས།
  author: ''
  volumes:
    05cc8b7421264b31a9db65c16a8e4cd8:
      image_group_id: I1KG5895
      title: ''
      volume_number: 1
      total_pages: 286
