id: P000643
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:55:37.165791
source_metadata:
  id: bdr:W1KG5875
  title: མཆོད་རྟེན་དང་ཚ་ཚ་གདབ་པའི་ཆོ་གའི་གཞུང་གསུམ་ཕྱོགས་གཏུས།
  author: ''
  volumes:
    05cc8b7421264b31a9db65c16a8e4cd8:
      image_group_id: I1KG5895
      title: ''
      volume_number: 1
      total_pages: 286
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
