id: I638A5212
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:04:25+00:00'
last_modified: '2022-06-07T12:32:32.414143+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5875
  title: མཆོད་རྟེན་དང་ཚ་ཚ་གདབ་པའི་ཆོ་གའི་གཞུང་གསུམ་ཕྱོགས་གཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    715E:
      image_group_id: I1KG5895
      title: ''
      total_pages: 286
      order: 1
      base_file: 715E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
